### ISSUE TITLE
Problems about input files

### ISSUE THREAD

**Issue by liuzh47** [taoqi98/UniFedRec#1]
How can we obtain the files `train_sam2.tsv`, `val_sam2.tsv` and `mind_large_news_scoring_dict.pickle` for training the `Main.ipynb` script?  These files are not included in the MIND large dataset. 

Could you provide the preprocessing script to obtain these files?

**Comment by taoqi98** [comment]
Hi, thank you for your attention to our work.
1. The train_sam2.tsv is exactly the MINDlarge_train/behaviors.tsv, and val_sam2.tsv is exactly the  MINDlarge_dev/behaviors.tsv. I renamed these files in my experiments and forgot to clarify this point in the released codes.
2. docs_train_dev.tsv file is the merged version of the MINDlarge_train/news.tsv and MINDlarge_dev/news.tsv.
3. The mind_large_news_scoring_dict.pickle is the news embedding generated by the news ranking model. You can download this file via https://drive.google.com/file/d/1BkmKHamLMgSXzc3LUGPYoAkGoBqOmRYz/view?usp=sharing

**Comment by liuzh47** [comment]
Thanks for the clarification!

**Comment by liuzh47** [comment]
>The mind_large_news_scoring_dict.pickle is the news embedding generated by the news ranking model. 

Do you mean the news embedding is generated by the news encoder in the FedRec system? I notice the news representation in this work is of dimension 256, while the FedRec represents the news with a dimension size of 400. Do I need to retrain the whole FedRec model with news dimension of 256 to get the news embedding?

**Comment by taoqi98** [comment]
You do not need to rerun FedNewsRec. In the experiments of our work, we have employed the FedNewsRec method to train the ranking recommendation model and employ the news model of it to generate news embeddings. And the generated news embeddings are attacked in the link I shared with you. Besides, for the efficiency issues, in experiments of the UniFedRec work, we set the dimensionality of embeddings to 256, instead of 400 (the setting of the original FedNewsRec paper), which is a minor change in hyper-parameters.

**Comment by taoqi98** [comment]
> > The mind_large_news_scoring_dict.pickle is the news embedding generated by the news ranking model.
> 
> Do you mean the news embedding is generated by the news encoder in the FedRec system? I notice the news representation in this work is of dimension 256, while the FedRec represents the news with a dimension size of 400. Do I need to retrain the whole FedRec model with news dimension of 256 to get the news embedding?

Thank you for your attention to our work. You do not need to rerun FedNewsRec. In the experiments of our work, we have employed the FedNewsRec method to train the ranking recommendation model and employ the news model of it to generate news embeddings. And the generated news embeddings are attacked in the link I shared with you. Besides, for the efficiency issues, in experiments of the UniFedRec work, we set the dimensionality of embeddings to 256, instead of 400 (the setting of the original FedNewsRec paper), which is a minor change in hyper-parameters.
